version: '3'
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    labels:
      - "traefik.frontend.rule=Host:theholloways.dev"
      - "traefik.enable=true"
      - "traefik.docker.network=reverseproxy_default"
    networks:
    - "reverseproxy_default"

networks:
  reverseproxy_default:
    external:
      name: reverseproxy_default